version: '2'

services:
  chat-client:
    build: ./client
    volumes:
      - ./client:/code
    ports:
      - "8000:8000"
    command: npm run dev
  chat-api:
    build: ./api
    volumes:
      - ./api:/code
    ports:
      - "3000:3000"
    command: npm run start:dev
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    tty: true
    stdin_open: true
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '13306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: